[FATAL][models.go:27]2020/10/21 15:41:45 [dial tcp 39.98.122.209:3306: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.]
[FATAL][models.go:27]2020/10/21 15:45:13 [dial tcp: lookup 8vb6025810x4n11s8wo.mysql.zhangbei.rds.aliyuncs.com: no such host]
[INFO][udp.go:110]2020/10/21 15:47:19 [sql: database is closed]
[INFO][udp.go:163]2020/10/21 15:47:19 [sql: database is closed]
[INFO][receive.go:71]2020/10/21 15:47:19 [sql: database is closed]
[FATAL][models.go:27]2020/10/21 15:47:51 [dial tcp: lookup 8vb6025810x4n11s8wo.mysql.zhangbei.rds.aliyuncs.com: no such host]
